# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Deixa o Hibernate criar o schema
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Ativa o console (opcional)
spring.h2.console.enabled=true
